"""updated_problem_table

Revision ID: 0f7cc3c1d640
Revises: 43a9886c728f
Create Date: 2025-05-02 07:38:15.961766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f7cc3c1d640'
down_revision: Union[str, None] = '43a9886c728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'created_at')
    op.drop_column('problems', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
