"""add_created_at_to_problems_with_default

Revision ID: b7ce99ae3a06
Revises: 0f7cc3c1d640
Create Date: 2025-05-02 08:02:06.129310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'b7ce99ae3a06'
down_revision: Union[str, None] = '0f7cc3c1d640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE problems SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # Make the column non-nullable
    op.alter_column('problems', 'created_at',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'created_at')
    # ### end Alembic commands ###
